<?php
// config/lang_en.php
// Translation array for English language

return [
    'home' => 'Home',
    'ita' => 'ITA Online',
    'information_system' => 'Information Portals',
    'sgs' => 'SGS System (Grades)',
    'dmc' => 'DMC System (Students)',
    'obec' => 'OBEC Website',
    'emis' => 'EMIS Information System',
    'gpa' => 'GPA System (Binet)',
    'admin_panel' => 'Staff / Admin Portal',
    'admin_dashboard' => 'Admin Dashboard',
    'logout' => 'Logout',
    'welcome_school' => 'Welcome to our institution',
    'hero_title' => 'Driving Future with <br> <span class="text-gradient-primary">Innovation & Technology</span>',
    'hero_desc' => 'We focus on academic excellence, core values, and modern technology. We build trust through our transparent and accountable school management platform, ITA Online.',
    'check_ita' => 'Check ITA Online',
    'read_news' => 'Read News & PR',
    'slider1_title' => 'Computing and Innovation Hub',
    'slider1_desc' => 'Advanced computer labs and robotic kits designed for analysis and creation of scientific innovations.',
    'slider2_title' => 'Global Quality Educational Standard',
    'slider2_desc' => 'A bilingual curriculum promoting critical thinking, preparing students for success in the creative economy.',
    'ita_status' => 'Integrity & Transparency (ITA Online)',
    'ita_status_desc' => 'Annual performance reports and public documents index, evaluating indicators O1 - O43 for the current fiscal year.',
    'published_stats' => 'Published %d of %d indicators',
    'view_ita_table' => 'View Indicators',
    'external_portals' => 'External System Portals',
    'external_portals_desc' => 'Quick links to national educational systems for administration, teachers, and students.',
    'news_section_title' => 'School News & Press Release',
    'news_section_desc' => 'Latest events, official announcements, and public relations directly from the school.',
    'all' => 'All',
    'announcement' => 'Announcements',
    'activity' => 'Activities',
    'general' => 'General PR News',
    'no_news' => 'No school news published at this moment.',
    'read_more' => 'Read More',
    'by' => 'By',
    'pdpa_title' => 'We Value Your Privacy',
    'pdpa_desc' => 'This website uses cookies to analyze traffic and improve user experience, in compliance with the Personal Data Protection Act (PDPA).',
    'pdpa_accept' => 'Accept All Cookies',
    'pdpa_reject' => 'Reject Non-essential Cookies',
    'contact_us' => 'Contact Us',
    'address' => '123 Witthayasartpattana Rd., Nai Mueang, Mueang, Tak 63000',
    'tel' => '055-123456',
    'privacy_policy' => 'Privacy Policy',
    'terms_of_use' => 'Terms of Use',
    'search_placeholder' => 'Search indicators (e.g. Structure, O1, Plan)...',
    'oit_code' => 'OIT Code',
    'oit_title' => 'Indicator / Publication Topic',
    'oit_download' => 'Link / Document Download',
    'oit_updated' => 'Last Updated',
    'download_pdf' => 'Download PDF',
    'view_link' => 'View Source Link',
    'waiting_update' => 'Under Construction',
    'ita_showcase' => 'ITA Online Dashboard (OIT)',
    'ita_showcase_desc' => 'Open Data Integrity and Transparency Assessment for Educational Institutions under NACC guidelines.',
    
    // About School Translations
    'about_school' => 'About School',
    'history' => 'School History',
    'vision_mission' => 'Vision & Mission',
    'symbol' => 'School Symbols',
    'colors' => 'School Colors',
    'song' => 'School Song',
    'executives' => 'Executive Directory',
    'structure' => 'Administrative Structure',
];
