-- SQL Database Setup Script for School Website and ITA Management System
-- Database: `school_db`

CREATE DATABASE IF NOT EXISTS `school_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `school_db`;

-- 1. Table `users` (For personnel, teachers, and admins)
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `role` ENUM('admin', 'teacher') NOT NULL DEFAULT 'teacher',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Table `news` (For news, activities, and announcements)
CREATE TABLE IF NOT EXISTS `news` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `category` ENUM('general', 'activity', 'announcement') NOT NULL DEFAULT 'general',
  `image_url` VARCHAR(255) DEFAULT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Table `ita_items` (For ITA Online Indicators O1 - O43)
CREATE TABLE IF NOT EXISTS `ita_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(10) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `link_url` VARCHAR(500) DEFAULT NULL,
  `file_path` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed default Administrator account (Username: admin, Password: admin123)
-- Hash generated by PHP: password_hash('admin123', PASSWORD_BCRYPT)
INSERT INTO `users` (`id`, `username`, `password`, `fullname`, `role`) VALUES
(1, 'admin', '$2y$10$QHE9kSn3LpGTVp3tyT2BvetC.3KRsH6Eb0NUouVF76jQ9Xk476Ggq', 'ผู้ดูแลระบบสูงสุด', 'admin')
ON DUPLICATE KEY UPDATE `password` = VALUES(`password`), `fullname` = VALUES(`fullname`);

-- Seed default O1-O43 ITA Online Indicators
INSERT INTO `ita_items` (`code`, `name`, `link_url`, `file_path`, `status`) VALUES
('O1', 'โครงสร้างหน่วยงาน', NULL, NULL, 'published'),
('O2', 'ข้อมูลผู้บริหาร', NULL, NULL, 'published'),
('O3', 'อำนาจหน้าที่', NULL, NULL, 'published'),
('O4', 'แผนปฏิบัติราชการประจำปี / แผนพัฒนาหน่วยงาน', NULL, NULL, 'published'),
('O5', 'ข้อมูลการติดต่อหน่วยงาน', NULL, NULL, 'published'),
('O6', 'กฎหมายที่เกี่ยวข้อง', NULL, NULL, 'published'),
('O7', 'ข่าวประชาสัมพันธ์', NULL, NULL, 'published'),
('O8', 'Q&A (ช่องทางการตอบข้อซักถาม)', NULL, NULL, 'published'),
('O9', 'ช่องทางการรับฟังความคิดเห็น', NULL, NULL, 'published'),
('O10', 'แผนการดำเนินงานและงบประมาณประจำปี', NULL, NULL, 'published'),
('O11', 'รายงานการกำกับติดตามการดำเนินงานประจำปี รอบ 6 เดือน', NULL, NULL, 'published'),
('O12', 'รายงานผลการดำเนินงานประจำปี', NULL, NULL, 'published'),
('O13', 'คู่มือหรือมาตรฐานการปฏิบัติงานของเจ้าหน้าที่', NULL, NULL, 'published'),
('O14', 'คู่มือหรือมาตรฐานการให้บริการสำหรับประชาชน', NULL, NULL, 'published'),
('O15', 'ข้อมูลเชิงสถิติการให้บริการ', NULL, NULL, 'published'),
('O16', 'รายงานผลการสำรวจความพึงพอใจการให้บริการ', NULL, NULL, 'published'),
('O17', 'E-Service (การให้บริการในรูปแบบอิเล็กทรอนิกส์)', NULL, NULL, 'published'),
('O18', 'แผนการจัดซื้อจัดจ้างหรือแผนการจัดหาพัสดุ', NULL, NULL, 'published'),
('O19', 'ประกาศต่าง ๆ เกี่ยวกับการจัดซื้อจัดจ้างหรือการจัดหาพัสดุ', NULL, NULL, 'published'),
('O20', 'สรุปผลการจัดซื้อจัดจ้างหรือการจัดหาพัสดุรายเดือน (สขร.1)', NULL, NULL, 'published'),
('O21', 'รายงานผลการจัดซื้อจัดจ้างหรือการจัดหาพัสดุประจำปี', NULL, NULL, 'published'),
('O22', 'นโยบายการบริหารและพัฒนาทรัพยากรบุคคล', NULL, NULL, 'published'),
('O23', 'การดำเนินการตามนโยบายการบริหารและพัฒนาทรัพยากรบุคคล', NULL, NULL, 'published'),
('O24', 'หลักเกณฑ์การบริหารและพัฒนาทรัพยากรบุคคล', NULL, NULL, 'published'),
('O25', 'รายงานผลการบริหารและพัฒนาทรัพยากรบุคคลประจำปี', NULL, NULL, 'published'),
('O26', 'แนวปฏิบัติการจัดการเรื่องร้องเรียนการทุจริตและประพฤติมิชอบ', NULL, NULL, 'published'),
('O27', 'ช่องทางแจ้งเรื่องร้องเรียนการทุจริตและประพฤติมิชอบ', NULL, NULL, 'published'),
('O28', 'ข้อมูลเชิงสถิติเรื่องร้องเรียนการทุจริตและประพฤติมิชอบ', NULL, NULL, 'published'),
('O29', 'ช่องทางการรับฟังความคิดเห็นส่วนรวม', NULL, NULL, 'published'),
('O30', 'การเปิดโอกาสให้เกิดการมีส่วนร่วม', NULL, NULL, 'published'),
('O31', 'เจตนารมณ์หรือนโยบาย No Gift Policy', NULL, NULL, 'published'),
('O32', 'การสร้างวัฒนธรรม No Gift Policy', NULL, NULL, 'published'),
('O33', 'รายงานผลตามนโยบาย No Gift Policy', NULL, NULL, 'published'),
('O34', 'การประเมินความเสี่ยงเพื่อป้องกันการทุจริต', NULL, NULL, 'published'),
('O35', 'การดำเนินการเพื่อจัดการความเสี่ยงการทุจริตและประพฤติมิชอบ', NULL, NULL, 'published'),
('O36', 'แผนปฏิบัติการป้องกันการทุจริต', NULL, NULL, 'published'),
('O37', 'รายงานการกำกับติดตามการดำเนินการป้องกันการทุจริต รอบ 6 เดือน', NULL, NULL, 'published'),
('O38', 'รายงานผลการดำเนินการป้องกันการทุจริตประจำปี', NULL, NULL, 'published'),
('O39', 'ประมวลจริยธรรมสำหรับเจ้าหน้าที่ของรัฐ', NULL, NULL, 'published'),
('O40', 'การขับเคลื่อนจริยธรรม', NULL, NULL, 'published'),
('O41', 'การประเมินจริยธรรมเจ้าหน้าที่ของรัฐ', NULL, NULL, 'published'),
('O42', 'มาตรการส่งเสริมคุณธรรมและความโปร่งใสภายในหน่วยงาน', NULL, NULL, 'published'),
('O43', 'รายงานผลการดำเนินการเพื่อส่งเสริมคุณธรรมและความโปร่งใสภายในหน่วยงาน', NULL, NULL, 'published')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- Seed dummy news data for visual preview
INSERT INTO `news` (`title`, `content`, `category`, `image_url`, `created_by`) VALUES
('ประกาศผลสอบคัดเลือกนักเรียน ม.1 และ ม.4 ประจำปีการศึกษา 2026', 'โรงเรียนของเราขอประกาศผลการสอบคัดเลือกนักเรียนเข้าเรียนในระดับชั้นมัธยมศึกษาปีที่ 1 และ 4 ปีการศึกษา 2026 ผู้ที่ผ่านการคัดเลือกโปรดมารายงานตัวและมอบตัวตามวันเวลาที่กำหนด...', 'announcement', '/assets/images/news-1.jpg', 1),
('กิจกรรมวันวิทยาศาสตร์และเทคโนโลยี ประจำปีการศึกษา 2025', 'ภาพบรรยากาศการจัดกิจกรรมวันวิทยาศาสตร์และเทคโนโลยีประจำปีการศึกษา 2025 ของโรงเรียน มีกิจกรรมทดลองทางวิทยาศาสตร์ บูธนิทรรศการ และการแข่งขันชิงรางวัลมากมาย...', 'activity', '/assets/images/news-2.jpg', 1),
('ยินดีต้อนรับคณะผู้บริหารและครูสู่ปีการศึกษาใหม่ 2026', 'ยินดีต้อนรับคณะผู้บริหาร คณะครู และบุคลากรทางการศึกษาสู่การทำงานร่วมกันในปีการศึกษา 2026 นี้ มุ่งพัฒนาคุณภาพทางวิชาการและทักษะชีวิตของนักเรียนเป็นสำคัญ...', 'general', '/assets/images/news-3.jpg', 1);

-- 4. Table `school_info` (for rich text/HTML contents of sections)
CREATE TABLE IF NOT EXISTS `school_info` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `section_key` VARCHAR(50) NOT NULL UNIQUE,
  `content_th` LONGTEXT NOT NULL,
  `content_en` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Table `school_executives` (for executive list directory)
CREATE TABLE IF NOT EXISTS `school_executives` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name_th` VARCHAR(100) NOT NULL,
  `name_en` VARCHAR(100) NOT NULL,
  `position_th` VARCHAR(100) NOT NULL,
  `position_en` VARCHAR(100) NOT NULL,
  `period` VARCHAR(50) NOT NULL,
  `image_path` VARCHAR(255) DEFAULT NULL,
  `is_current` TINYINT(1) NOT NULL DEFAULT 0,
  `order_num` INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed data for `school_info`
INSERT INTO `school_info` (`section_key`, `content_th`, `content_en`) VALUES
('history', 
 '<div class="space-y-6">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2 flex items-center gap-2">
        <i class="fa-solid fa-clock-rotate-left text-indigo-500"></i> ประวัติความเป็นมาของโรงเรียนพิชัย
    </h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs sm:text-sm">
        โรงเรียนพิชัย ได้รับอนุญาตให้เปิดสอนเมื่อวันที่ ๑๗ พฤษภาคม ๒๔๙๔ โดยกระทรวงศึกษาธิการ อนุญาตให้เปิดโรงเรียนนี้เป็นโรงเรียนสามัญ ประเภทสหศึกษา ตามหนังสือของจังหวัดที่ ๑๐๕/๒๔๙๔ ลงวันที่ ๒๔ เมษายน ๒๔๙๔ ผู้ริเริ่มในการจัดตั้งคือ นายพุ่ม สราญรมย์ และนายเจียร เอี่ยมสกุล ทางราชการได้แต่งตั้ง ให้ นายพิศาล ชัยเพ็ชร มาเป็นครูใหญ่ และนายอุทัย เจริญกุล มาเป็นครูน้อย เปิดรับนักเรียนชั้นมัธยมศึกษาปีที่ ๑ ปีแรก มีนักเรียน ๔๒ คน อาศัยสถานที่โรงเรียนบ้านในเมือง เป็นที่เปิดการสอนในระยะแรก
    </p>
    <div class="relative pl-6 border-l-2 border-indigo-500/30 space-y-6 mt-6">
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">พ.ศ. ๒๔๙๔ (1951)</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">จัดตั้งสถาบันและเปิดทำการสอน</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                ริเริ่มจัดตั้งโดย นายพุ่ม สราญรมย์ และนายเจียร เอี่ยมสกุล มี นายพิศาล ชัยเพ็ชร เป็นครูใหญ่คนแรก มีนักเรียนระดับ ม.๑ จำนวน ๔๒ คน โดยอาศัยเรียนชั่วคราวที่โรงเรียนบ้านในเมือง
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">พ.ศ. ๒๔๙๕ (1952)</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">ก่อสร้างอาคารเรียนหลังแรก</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                ได้รับงบประมาณสร้างอาคารเรียนไม้ชั้นเดียว ขนาด ๑๕ x ๓๙ เมตร จำนวน ๕ ห้องเรียน และย้ายนักเรียนมาเรียนอย่างเป็นทางการ โดยมี นายศุภชัย สาชลวิจารณ์ เป็นครูใหญ่
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">พ.ศ. ๒๔๙๙ (1956) - ๒๕๐๓ (1960)</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">ความสำเร็จรุ่นแรกและการเปลี่ยนแผนการศึกษา</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                มีนักเรียนสำเร็จการศึกษา ม.๖ เป็นปีแรกในปี ๒๔๙๙ และต่อมาในปี ๒๕๐๓ ได้ปรับปรุงหลักสูตรการศึกษาเปิดสอน ม.ศ.๑ แทน โดยจัดระบบเป็น ๓ ระดับชั้น (ม.ศ.๑ - ๓)
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">พ.ศ. ๒๕๒๒ (1979) - ๒๕๓๕ (1992)</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">ขยายการศึกษาปลายและการเรียนวิชาชีพ</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                เปิดสอนระดับมัธยมศึกษาตอนปลายเป็นปีแรกในปี ๒๕๒๒ และขยายหลักสูตรประกาศนียบัตรวิชาชีพ (ปวช.) สาขาพาณิชยกรรมและบัญชีในปี ๒๕๓๕
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">พ.ศ. ๒๕๕๓ (2010) - ปัจจุบัน</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">ปรับทิศทางองค์กรและขนาดพื้นที่ปัจจุบัน</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                ยุบการสอนสายอาชีพ (ปวช.) เพื่อลดความซ้ำซ้อนเนื่องจากมีสถานศึกษาอาชีวะอยู่ในรัศมีใกล้เคียง ปัจจุบันโรงเรียนมีเนื้อที่รวมทั้งหมด ๖๙ ไร่ ๓ งาน ๔๒ ตารางวา
            </p>
        </div>
    </div>
 </div>',
 '<div class="space-y-6">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2 flex items-center gap-2">
        <i class="fa-solid fa-clock-rotate-left text-indigo-500"></i> History of Phichai School
    </h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs sm:text-sm">
        Phichai School was authorized to open on May 17, 1951, by the Ministry of Education as a co-educational general secondary school, following Provincial Order No. 105/2494 dated April 24, 1951. The pioneers of this establishment were Mr. Phum Saranrom and Mr. Chian Eiamsakul. Mr. Phisan Chaiphet was appointed as the first Headmaster, and Mr. Uthai Charoenkul as the assistant teacher. In the first year, it opened with 42 Mathayom 1 students, temporarily using the premises of Ban Nai Mueang School.
    </p>
    <div class="relative pl-6 border-l-2 border-indigo-500/30 space-y-6 mt-6">
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">1951</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">Foundation & Initial Instruction</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                Initiated by Mr. Phum Saranrom and Mr. Chian Eiamsakul. Mr. Phisan Chaiphet served as the headmaster. Classes started for 42 students at Ban Nai Mueang School premises.
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">1952</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">First School Building Construction</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                Received a budget of 150,000 Baht to construct a single-story wooden building (15 x 39 meters, 5 classrooms). Students were officially moved to this site under Headmaster Mr. Supachai Sachonwichan.
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">1956 - 1960</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">First Graduates & Restructuring</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                The first batch of Mathayom 6 students graduated in 1956. In 1960, the Mathayom 1 level was replaced by Mathayom Suksa 1 (M.S. 1), changing the structure to M.S. 1 - 3 levels.
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">1979 - 1992</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">Upper Secondary & Vocational Education</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                Upper-secondary school classes were introduced in 1979. Vocational Certificate (Voc. Cert.) programs in commerce and accounting were launched in 1992.
            </p>
        </div>
        <div>
            <span class="absolute -left-[31px] top-1 w-4 h-4 rounded-full bg-indigo-600 border-4 border-white dark:border-slate-900 shadow-md"></span>
            <span class="font-english font-bold text-indigo-600 dark:text-indigo-400 text-xs">2010 - Present</span>
            <h4 class="font-bold text-slate-900 dark:text-white text-xs mt-0.5">Academic Repositioning & School Grounds</h4>
            <p class="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                The vocational curriculum was discontinued in 2010 due to nearby vocational colleges within 20 km. The school campus currently covers 69 Rai, 3 Ngan, and 42 Square Wah.
            </p>
        </div>
    </div>
 </div>'
),
('vision_mission',
 '<div class="space-y-6">
    <div class="space-y-2">
        <h3 class="text-xl font-bold text-indigo-600 dark:text-indigo-400"><i class="fa-solid fa-eye mr-2"></i>วิสัยทัศน์ (Vision)</h3>
        <p class="leading-relaxed text-slate-600 dark:text-slate-300 italic border-l-4 border-indigo-500 pl-4">"มุ่งสร้างนักนวัตกรรมที่มีคุณภาพ คุณธรรม และความโปร่งใส ก้าวทันเทคโนโลยีและมีทักษะสากล"</p>
    </div>
    <div class="space-y-3">
        <h3 class="text-xl font-bold text-purple-600 dark:text-purple-400"><i class="fa-solid fa-bullseye mr-2"></i>พันธกิจ (Mission)</h3>
        <ul class="list-disc pl-5 space-y-2 text-slate-600 dark:text-slate-300 text-xs">
            <li>ส่งเสริมคุณภาพการศึกษาด้านวิทยาศาสตร์ นวัตกรรม และวิทยาการคำนวณสู่มาตรฐานสากล</li>
            <li>พัฒนาผู้เรียนให้มีคุณลักษณะอันพึงประสงค์ มีวินัย ความซื่อสัตย์สุจริต และรักการเรียนรู้</li>
            <li>ปฏิรูประบบการทำงานขององค์กรให้เปิดเผย โปร่งใส มีธรรมาภิบาล และมีระบบตรวจสอบที่เข้าถึงง่าย</li>
        </ul>
    </div>
 </div>',
 '<div class="space-y-6">
    <div class="space-y-2">
        <h3 class="text-xl font-bold text-indigo-600 dark:text-indigo-400"><i class="fa-solid fa-eye mr-2"></i>Vision</h3>
        <p class="leading-relaxed text-slate-600 dark:text-slate-300 italic border-l-4 border-indigo-500 pl-4">"To cultivate quality innovators with high ethics and transparency, excelling in modern tech and international competencies."</p>
    </div>
    <div class="space-y-3">
        <h3 class="text-xl font-bold text-purple-600 dark:text-purple-400"><i class="fa-solid fa-bullseye mr-2"></i>Mission</h3>
        <ul class="list-disc pl-5 space-y-2 text-slate-600 dark:text-slate-300 text-xs">
            <li>Foster computing science education and scientific research to achieve international standards.</li>
            <li>Nurture student behavior towards active learning, social responsibility, integrity, and ethics.</li>
            <li>Operate organization systems with complete open transparency, accountability, and governance.</li>
        </ul>
    </div>
 </div>'
),
('symbol',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">ตราสัญลักษณ์ประจำโรงเรียน</h3>
    <div class="flex flex-col md:flex-row items-center gap-6 mt-4">
        <div class="w-32 h-32 rounded-3xl bg-gradient-to-tr from-indigo-500 to-purple-600 flex items-center justify-center shadow-xl border border-indigo-400/20 text-white text-5xl font-english font-black">
            วส.
        </div>
        <div class="space-y-2 text-xs text-slate-600 dark:text-slate-300">
            <p><strong>ตราสัญลักษณ์:</strong> ตัวอักษรย่อ "วส." ในกรอบสี่เหลี่ยมโค้งมน ขนาบด้วยเกลียวคลื่นวิวัฒนาการและอะตอมอิเล็กตรอน</p>
            <p><strong>ความหมายของสัญลักษณ์:</strong></p>
            <ul class="list-disc pl-5 space-y-1">
                <li><strong>กรอบขอบโค้ง:</strong> ความยืดหยุ่นในการปรับตัวเข้ากับวิวัฒนาการทางสังคม</li>
                <li><strong>สัญลักษณ์อะตอม:</strong> พลังแห่งความรู้ด้านวิทยาศาสตร์และปัญญาประดิษฐ์</li>
                <li><strong>เกลียวคลื่นพลังงาน:</strong> ความเจริญก้าวหน้าที่เคลื่อนไหวไม่หยุดนิ่ง</li>
            </ul>
        </div>
    </div>
 </div>',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">School Badge & Symbols</h3>
    <div class="flex flex-col md:flex-row items-center gap-6 mt-4">
        <div class="w-32 h-32 rounded-3xl bg-gradient-to-tr from-indigo-500 to-purple-600 flex items-center justify-center shadow-xl border border-indigo-400/20 text-white text-5xl font-english font-black">
            ISS
        </div>
        <div class="space-y-2 text-xs text-slate-600 dark:text-slate-300">
            <p><strong>Badge:</strong> Abbreviation letters in a rounded-square envelope with evolutionary wave traces and electron atoms.</p>
            <p><strong>Symbol Meanings:</strong></p>
            <ul class="list-disc pl-5 space-y-1">
                <li><strong>Rounded Outer Frame:</strong> High adaptability and flexibility within global society changes.</li>
                <li><strong>Atom Element:</strong> Power of logic, computer sciences, and artificial intelligence.</li>
                <li><strong>Dynamic Waves:</strong> Continuous growth, innovation momentum, and forward movement.</li>
            </ul>
        </div>
    </div>
 </div>'
),
('colors',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">สีประจำโรงเรียน</h3>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
        <div class="p-4 bg-indigo-600 text-white rounded-2xl flex items-center gap-4 shadow border border-indigo-400/20">
            <span class="w-10 h-10 rounded-full bg-white block"></span>
            <div>
                <h4 class="font-bold text-sm">สีน้ำเงินคราม (Indigo Navy)</h4>
                <p class="text-[10px] text-indigo-200">หมายถึง ความมั่นคง ปัญญา และนวัตกรรมเทคโนโลยี</p>
            </div>
        </div>
        <div class="p-4 bg-white text-slate-900 border border-slate-200 rounded-2xl flex items-center gap-4 shadow">
            <span class="w-10 h-10 rounded-full bg-indigo-600 block"></span>
            <div>
                <h4 class="font-bold text-sm">สีขาวบริสุทธิ์ (Pure White)</h4>
                <p class="text-[10px] text-slate-500">หมายถึง ความโปร่งใส ความซื่อสัตย์ และมีคุณธรรมประจำใจ</p>
            </div>
        </div>
    </div>
 </div>',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">School Colors</h3>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
        <div class="p-4 bg-indigo-600 text-white rounded-2xl flex items-center gap-4 shadow border border-indigo-400/20">
            <span class="w-10 h-10 rounded-full bg-white block"></span>
            <div>
                <h4 class="font-bold text-sm">Indigo Navy</h4>
                <p class="text-[10px] text-indigo-200">Represents wisdom, stability, and technological innovation.</p>
            </div>
        </div>
        <div class="p-4 bg-white text-slate-900 border border-slate-200 rounded-2xl flex items-center gap-4 shadow">
            <span class="w-10 h-10 rounded-full bg-indigo-600 block"></span>
            <div>
                <h4 class="font-bold text-sm">Pure White</h4>
                <p class="text-[10px] text-slate-500">Represents purity, accountability, transparency, and integrity.</p>
            </div>
        </div>
    </div>
 </div>'
),
('song',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">เพลงมาร์ชโรงเรียน</h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs">เพลงมาร์ชสถาบันนวัตกรรม ร่วมร้องเฉลิมฉลองด้วยความภาคภูมิใจในเทคโนโลยีและคุณงามความดี</p>
    
    <!-- Audio Player Embed -->
    <div class="p-4 bg-indigo-500/10 border border-indigo-500/20 rounded-2xl flex flex-col gap-3 mt-4">
        <span class="text-xs font-bold text-indigo-600 dark:text-indigo-400"><i class="fa-solid fa-music mr-1.5"></i>เปิดฟังก์ชั่นเล่นไฟล์เสียงเพลงโรงเรียน</span>
        <audio controls class="w-full">
            <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg">
            เบราว์เซอร์ของคุณไม่สนับสนุนตัวเล่นเสียงนี้
        </audio>
    </div>

    <!-- YouTube Embed Video Frame -->
    <div class="relative w-full aspect-video rounded-2xl overflow-hidden border border-white/10 mt-6 shadow-lg bg-slate-950 flex items-center justify-center">
        <iframe class="w-full h-full" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="School Song Video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
 </div>',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">Official School Song</h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs">Sing with pride, honoring innovation, friendship, and moral integrity.</p>
    
    <!-- Audio Player Embed -->
    <div class="p-4 bg-indigo-500/10 border border-indigo-500/20 rounded-2xl flex flex-col gap-3 mt-4">
        <span class="text-xs font-bold text-indigo-600 dark:text-indigo-400"><i class="fa-solid fa-music mr-1.5"></i>Listen to School March (Audio)</span>
        <audio controls class="w-full">
            <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg">
            Your browser does not support the audio player.
        </audio>
    </div>

    <!-- YouTube Video Frame -->
    <div class="relative w-full aspect-video rounded-2xl overflow-hidden border border-white/10 mt-6 shadow-lg bg-slate-950 flex items-center justify-center">
        <iframe class="w-full h-full" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="School March Video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
 </div>'
),
('structure',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">โครงสร้างการบริหารงานองค์กร</h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs">แผนผังแสดงโครงสร้างอำนาจหน้าที่และการแบ่งฝ่ายรับผิดชอบในการบริหารงานของสถาบัน</p>
    
    <!-- Org Structure Flowchart Representation (SVG) -->
    <div class="p-6 bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-white/10 rounded-2xl shadow-inner mt-4 overflow-x-auto flex justify-center">
        <svg class="w-full max-w-lg text-slate-800 dark:text-white font-sans text-xs" viewBox="0 0 400 300">
            <!-- Node: Director -->
            <rect x="140" y="20" width="120" height="40" rx="8" fill="#4f46e5" stroke="#6366f1" stroke-width="1.5" />
            <text x="200" y="44" fill="#ffffff" font-weight="bold" text-anchor="middle">ผู้อำนวยการโรงเรียน</text>
            
            <!-- Connection Lines -->
            <line x1="200" y1="60" x2="200" y2="120" stroke="#6366f1" stroke-width="2" />
            <line x1="80" y1="120" x2="320" y2="120" stroke="#6366f1" stroke-width="2" />
            <line x1="80" y1="120" x2="80" y2="160" stroke="#6366f1" stroke-width="2" />
            <line x1="200" y1="120" x2="200" y2="160" stroke="#6366f1" stroke-width="2" />
            <line x1="320" y1="120" x2="320" y2="160" stroke="#6366f1" stroke-width="2" />
            
            <!-- Node: Academic -->
            <rect x="20" y="160" width="120" height="45" rx="8" fill="rgba(99, 102, 241, 0.1)" stroke="#6366f1" stroke-width="1" />
            <text x="80" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-indigo-300">ฝ่ายวิชาการ</text>
            
            <!-- Node: Administrative -->
            <rect x="140" y="160" width="120" height="45" rx="8" fill="rgba(168, 85, 247, 0.1)" stroke="#a855f7" stroke-width="1" />
            <text x="200" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-purple-300">ฝ่ายแผนและบริหาร</text>
            
            <!-- Node: Activities -->
            <rect x="260" y="160" width="120" height="45" rx="8" fill="rgba(236, 72, 153, 0.1)" stroke="#ec4899" stroke-width="1" />
            <text x="320" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-pink-300">ฝ่ายกิจการนักเรียน</text>
        </svg>
    </div>
 </div>',
 '<div class="space-y-4">
    <h3 class="text-xl font-bold text-slate-900 dark:text-white border-b border-slate-200 dark:border-slate-800 pb-2">Administrative Structure</h3>
    <p class="leading-relaxed text-slate-600 dark:text-slate-300 text-xs">Organizational flowchart showing structural divisions of school authority and responsibilities.</p>
    
    <!-- Org Structure Flowchart Representation (SVG) -->
    <div class="p-6 bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-white/10 rounded-2xl shadow-inner mt-4 overflow-x-auto flex justify-center">
        <svg class="w-full max-w-lg text-slate-800 dark:text-white font-sans text-xs" viewBox="0 0 400 300">
            <!-- Node: Director -->
            <rect x="140" y="20" width="120" height="40" rx="8" fill="#4f46e5" stroke="#6366f1" stroke-width="1.5" />
            <text x="200" y="44" fill="#ffffff" font-weight="bold" text-anchor="middle">School Director</text>
            
            <!-- Connection Lines -->
            <line x1="200" y1="60" x2="200" y2="120" stroke="#6366f1" stroke-width="2" />
            <line x1="80" y1="120" x2="320" y2="120" stroke="#6366f1" stroke-width="2" />
            <line x1="80" y1="120" x2="80" y2="160" stroke="#6366f1" stroke-width="2" />
            <line x1="200" y1="120" x2="200" y2="160" stroke="#6366f1" stroke-width="2" />
            <line x1="320" y1="120" x2="320" y2="160" stroke="#6366f1" stroke-width="2" />
            
            <!-- Node: Academic -->
            <rect x="20" y="160" width="120" height="45" rx="8" fill="rgba(99, 102, 241, 0.1)" stroke="#6366f1" stroke-width="1" />
            <text x="80" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-indigo-300">Academic Affairs</text>
            
            <!-- Node: Administrative -->
            <rect x="140" y="160" width="120" height="45" rx="8" fill="rgba(168, 85, 247, 0.1)" stroke="#a855f7" stroke-width="1" />
            <text x="200" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-purple-300">Planning & Finance</text>
            
            <!-- Node: Activities -->
            <rect x="260" y="160" width="120" height="45" rx="8" fill="rgba(236, 72, 153, 0.1)" stroke="#ec4899" stroke-width="1" />
            <text x="320" y="187" font-weight="bold" text-anchor="middle" class="fill-slate-800 dark:fill-pink-300">Student Affairs</text>
        </svg>
    </div>
 </div>'
);

-- Seed data for `school_executives`
INSERT INTO `school_executives` (`name_th`, `name_en`, `position_th`, `position_en`, `period`, `image_path`, `is_current`, `order_num`) VALUES
('ดร. อดิศร รัตนภาคี', 'Dr. Adisorn Rattanapakhi', 'ผู้อำนวยการโรงเรียน', 'School Director', '2564 - ปัจจุบัน (2021 - Present)', NULL, 1, 10),
('นางมนัชญา วงศ์วิทยา', 'Mrs. Manatchaya Wongwittaya', 'รองผู้อำนวยการฝ่ายวิชาการ', 'Deputy Director of Academic Affairs', '2565 - ปัจจุบัน (2022 - Present)', NULL, 1, 20),
('นายพีรพล พลวิโรจน์', 'Mr. Peerapol Ponviroj', 'อดีตผู้อำนวยการโรงเรียน', 'Former School Director', '2558 - 2564 (2015 - 2021)', NULL, 0, 30),
('ดร. เกียรติศักดิ์ อุดมวิทยา', 'Dr. Kiattisak Udomwittaya', 'อดีตผู้อำนวยการโรงเรียน', 'Former School Director', '2548 - 2558 (2005 - 2015)', NULL, 0, 40);

